# Generated by Django 5.2.1 on 2025-07-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_workoutlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='user',
        ),
    ]
